---
  - name: Install Dependencies
    hosts: all
    tasks:
    - name: Install python and deps
      package: 
        name: "{{ var_python_deps }}"
        state: present
  - name: Deploy Database 
    hosts: db
    roles:
    - db-webapp
  - name: Deploy Web Application
    hosts: web
    roles:
    - flask-webapp

              

        