---
#Python Dependencies
#apt-get install -y python python-setuptools python-dev build-essential python-pip python-mysqldb
var_python_deps:
  - python
  - python-setuptools
  - python-dev
  - build-essential
  - python-pip
  - python-mysqldb
